---
date: YYYY-MM-DD
last_modified_at: YYYY-MM-DD

title: "Title of the Page or Essay"
series: "Optional Series Name"
excerpt: >
  One-sentence summary or abstract of the post.
  (Wraps automatically, so no need for quotes.)

tags:
  - tag-one
  - tag-two
  - tag-three

keywords:
  - keyword one
  - keyword two
  - keyword three
---
